openapi: 3.0.0
info:
  title: Notes API with Authentication
  version: 1.0.0
  description: API documentation for the Notes application with JWT authentication.
servers:
  - url: http://localhost:3000
tags:
  - name: Auth
    description: User authentication
  - name: Notes
    description: The notes managing API
paths:
  /api/users/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "201":
          description: User registered successfully
  /api/users/login:
    post:
      tags: [Auth]
      summary: Login a user and get a token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: Successful login
  /api/notes:
    get:
      tags: [Notes]
      summary: Returns the list of notes for the authenticated user
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The page number to retrieve.
        - in: query
          name: limit
          schema:
            type: integer
          description: The number of notes to return per page.
      responses:
        "200":
          description: The list of the user's notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
        "401":
          description: Not authorized
    post:
      tags: [Notes]
      summary: Create a new note
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "401":
          description: Not authorized
  /api/notes/search:
    get:
      tags: [Notes]
      summary: Search notes by title
      description: Searches notes for the authenticated user based on a query string. Matches up to 3 words from the query.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
          required: true
          description: The search term for the note title.
      responses:
        "200":
          description: A list of matching notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
        "401":
          description: Not authorized
  /api/notes/{id}:
    get:
      tags: [Notes]
      summary: Get a note by id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "401":
          description: Not authorized
        "404":
          description: Note not found
    put:
      tags: [Notes]
      summary: Update a note by id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Note"
      responses:
        "200":
          description: Success
        "401":
          description: Not authorized
        "404":
          description: Note not found
    delete:
      tags: [Notes]
      summary: Remove a note by id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "401":
          description: Not authorized
        "404":
          description: Note not found
components:
  schemas:
    Note:
      type: object
      required:
        - title
        - content
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
